project:
  type: website
  output-dir: docs

website:
  page-footer: "\u00a9 2023 Trevor Ruiz"
  google-analytics: "G-H3YKZX4J88"
  # reader-mode: true
  repo-url: "https://github.com/pstat197/pstat197.github.io"
  sidebar:
    title: "Data Science Capstone"
    style: "docked"
    collapse-level: 1
    search: true
    logo: "img/ucsbds_hex.png"
    tools: 
      - icon: github
        href: https://github.com/pstat197
      - icon: slack
        href: https://ucsbdscapstone.slack.com
    contents:
      - about.qmd
      - people.qmd
      - section: "Projects"
        contents:
        - projects/projects-22-23.qmd
        - projects/projects-21-22.qmd
        - projects/projects-20-21.qmd
      - section: "Class materials"
        contents:
          - section: "PSTAT197A"
            contents:
              - pstat197a/about-syllabus.qmd
              - pstat197a/about-materials.qmd
          - section: "PSTAT197B-C"
            contents:
              - pstat197bc/about-syllabus.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

