---
title: "About"
---

The capstone aims to provide students with hands-on research training and career development opportunities related to data science. It is equally suitable for students interested in entering the job market as it is for those considering graduate school -- we partner with both industry and academic project sponsors to offer research experiences spanning a breadth of application domains.

# Students

For participating students, the capstone is a year-long course sequence comprising two distinct portions: a preparatory course in data science topics and collaborative research skills (PSTAT197A/CMPSC190DD, offered fall term) and two experiential learning courses in which students work in teams on interdisciplinary projects sponsored by an external partner and advised by a technical specialist (PSTAT197B-C/CMPSC190DE-DF, offered winter and spring terms). The course sequence culminates with a public showcase of student work.

The capstone is designed primarily for senior students of any discipline having an intermediate level of experience with applied quantitative methods of any kind and some exposure to programming. It is not expected that students will have obtained any specialized background or completed advanced coursework prior to participating, and students from non-PSTAT major programs are especially encouraged to apply. Here you can find information on eligibility, how to apply, and program outcomes.

::: callout-note
## At a glance

-   50-60 seats available each year

-   Participation is by application only; applications open in Spring quarter for the following year and are reviewed in week 5 and on a rolling basis thereafter

-   Eligibility requirements:

    -   junior or senior standing by fall quarter of the program year;

    -   strong academic record;

    -   motivation and interest in research;

    -   prior experience with computing, statistics and probability, and regression

-   Students must make a full year commitment -- enroll in one 4-credit course each quarter -- to participate

-   Specialized or advanced training in statistical modeling, machine learning, computing, data science, etc., ***not required for non-PSTAT students***

-   Non-PSTAT students are especially encouraged to apply
:::

## What to expect

Students can expect to gain training and skills in collaborative data science and produce a strong work sample by the end of the program. All students will prepare a poster presentation for a public showcase of student work toward the end of the year. Posters will also be published online.

Depending on the project, students may also contribute during or after the project work period to other outputs such as public repositories, software products, conference presentations, or publications.

Besides project outputs, students receive mentorship from their project advisors throughout the course of the experiential learning component of the capstone. Students also gain access to the network of current and past participants and project sponsors for career development purposes.

## Prerequisites and eligibility

The prerequisites for the capstone are exposure to (1) computing, (2) statistics and probability, and (3) regression. Since the program is interdisciplinary and intended to be accessible to non-PSTAT majors, these requirements are not strictly tied to any specific courses.

For the PSTAT student, completion of regression analysis (PSTAT126) should suffice. For the non-PSTAT student, any prior experience with statistical concepts, quantitative models, and computing will be considered.

Students should be of junior or senior standing by the term they would begin the capstone (*i.e.,* fall of the year of application). A full-year commitment is expected to participate, so seniors expecting to graduate early may not be eligible. Younger students, even if otherwise eligible, will be encouraged to reapply in a later year.

Students should have a strong academic record and be motivated to learn independently and work on a research problem.

# Sponsors

For participating project sponsors, the program offers opportunities to engage in mentorship, advance research agendas, and establish collaborative partnerships.

Data science capstone projects at UCSB are, above all, about creating educational and professional opportunities for students. We want to work with project sponsors who share our commitment to student learning.

Participation can benefit sponsors by providing pilot research or advancing existing projects, and can also provide opportunities to form new partnerships and collaborations and potentially recruit talent.

## Tips for success

We have found that successful projects include students in making novel contributions to a broader research agenda based on concrete starting points. In other words, projects tend to be productive when there is a clear focus and purpose. In our view, mutually beneficial success is most likely when sponsors:

-   are invested in students' intellectual and professional development;

-   have identified a well-defined data science problem of clear value to their agenda or organization;

-   can provide initial work (analysis, codes, relevant literature) and hands-on direction and training to students at the beginning of the project to facilitate a quick start.

Projects tend to be less productive in the absence of very specific direction and engagement on the part of the sponsor at the outset of the project -- this often results in protracted exploratory analyses lacking focus. Typically, given the proper initial support, students are able to make ongoing progress with a fair degree of autonomy after a few weeks.

## Timeline

Project work takes place in winter and spring quarters each year. As such, we follow this approximate timeline:

-   *June -- October*: project recruitment for upcoming year

-   *October -- November*: development of project plans in collaboration with sponsors

-   *December*: assignment of students and a faculty or graduate student advisor to the project

-   *January*: project work begins

-   *June*: project work concludes with poster showcase on UCSB's campus

The general expectation is that datasets are in hand by the time project work begins. However, in some cases, projects may start with pilot data.

## Logistics

Sponsors provide:

-   project objectives and datasets;

-   an advisor available to meet for one hour weekly or biweekly with the project team (virtual meetings ok) during the working period (January -- June);

-   (non-UCSB-affiliated sponsors only) a participation fee to support the project showcase and prizes for best projects

UCSB provides:

-   consultation on project plan development;

-   at least one faculty or graduate student co-advisor to join project meetings and assist students in meeting project goals;

-   student research team matched to the project based on interests and skills;

-   meeting space and research computing resources.

## Disclosure agreements

Sponsors may wish to establish disclosure agreements covering the scope of project work. Typically such agreements pertain to data and information provided by the project sponsor for educational purposes, and are entered into by the university with the support of capstone program staff. Any such agreements are binding on students and faculty as university representatives.

In the 2023-2024 academic year we will be providing a standard nondisclosure agreement on request. We are happy to consider modifications to the standard agreement provided they are not overly restrictive -- students will need to discuss their work with the class and prepare a public poster presentation in order to earn university credit. It should be noted that the university cannot enter into agreements pertaining to ownership of project deliverables -- students retain rights to work that they produce for academic credit.
